config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.root      :controller => "home", :action => "index"
  map.resource  :authentication
  map.resources :users, :member => { :avatar => :get, :upload_avatar => :put, :password => :get, :change_password => :put }
  map.resources :passwords
  map.resources :comments
  map.resources :emails

  map.resources :tasks,
    :collection => {
      :auto_complete => :post
    },
    :member => {
      :complete => :put
    }

  map.resources :leads,
    :has_many => [ :comments, :emails ],
    :collection => {
      :auto_complete => :post,
      :options => :get,
      :redraw  => :post,
      :search  => :get
    },
    :member => {
      :attach  => :put,
      :convert => :get,
      :discard => :post,
      :promote => :put,
      :reject  => :put
    }

  [ :accounts, :campaigns, :contacts, :opportunities ].each do |resource|
    map.resources resource,
      :has_many => [ :comments, :emails ],
      :collection => {
        :auto_complete => :post,
        :options => :get,
        :redraw  => :post,
        :search  => :get
      },
      :member => {
        :attach  => :put,
        :discard => :post
      }
  end

  map.signup  "signup",  :controller => "users",           :action => "new"
  map.profile "profile", :controller => "users",           :action => "show"
  map.login   "login",   :controller => "authentications", :action => "new"
  map.logout  "logout",  :controller => "authentications", :action => "destroy"
  map.admin   "admin",   :controller => "admin/users",     :action => "index"

  map.namespace :admin do |admin|
    admin.resources :users, :collection => { :search => :get, :auto_complete => :post }, :member => { :suspend => :put, :reactivate => :put, :confirm => :get }
    admin.resources :settings
    admin.resources :plugins
  end

  

  
  map.connect ":controller/:action/:id"
  map.connect ":controller/:action/:id.:format"
end

app/models/lead.rb
# Fat Free CRM
# Copyright (C) 2008-2010 by Michael Dvorkin
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

# == Schema Information
# Schema version: 27
#
# Table name: leads
#
#  id              :integer(4)      not null, primary key
#  user_id         :integer(4)
#  campaign_id     :integer(4)
#  assigned_to     :integer(4)
#  first_name      :string(64)      default(""), not null
#  last_name       :string(64)      default(""), not null
#  access          :string(8)       default("Private")
#  title           :string(64)
#  company         :string(64)
#  source          :string(32)
#  status          :string(32)
#  referred_by     :string(64)
#  email           :string(64)
#  alt_email       :string(64)
#  phone           :string(32)
#  mobile          :string(32)
#  blog            :string(128)
#  linkedin        :string(128)
#  facebook        :string(128)
#  twitter         :string(128)
#  rating          :integer(4)      default(0), not null
#  do_not_call     :boolean(1)      not null
#  deleted_at      :datetime
#  created_at      :datetime
#  updated_at      :datetime
#  background_info :string(255)
#
class Lead < ActiveRecord::Base
  belongs_to  :user
  belongs_to  :campaign
  belongs_to  :assignee, :class_name => "User", :foreign_key => :assigned_to
  has_one     :contact, :dependent => :nullify # On destroy keep the contact, but nullify its lead_id
  has_many    :tasks, :as => :asset, :dependent => :destroy, :order => 'created_at DESC'
  has_many    :activities, :as => :subject, :order => 'created_at DESC'
  has_one     :business_address, :dependent => :destroy, :as => :addressable, :class_name => "Address", :conditions => "address_type='Business'"
  has_many    :emails, :as => :mediator
  
  accepts_nested_attributes_for :business_address, :allow_destroy => true
  
  named_scope :only, lambda { |filters| { :conditions => [ "status IN (?)" + (filters.delete("other") ? " OR status IS NULL" : ""), filters ] } }
  named_scope :converted, :conditions => "status='converted'"
  named_scope :for_campaign, lambda { |id| { :conditions => [ "campaign_id=?", id ] } }
  named_scope :created_by, lambda { |user| { :conditions => [ "user_id = ?" , user.id ] } }
  named_scope :assigned_to, lambda { |user| { :conditions => ["assigned_to = ? " , user.id ] } }

  simple_column_search :first_name, :last_name, :company, :email,
    :match => lambda { |column| column == :email ? :middle : :start },
    :escape => lambda { |query| query.gsub(/[^\w\s\-\.']/, "").strip }
  uses_user_permissions
  acts_as_commentable
  acts_as_paranoid
  sortable :by => [ "first_name ASC", "last_name ASC", "company ASC", "rating DESC", "created_at DESC", "updated_at DESC" ], :default => "created_at DESC"

  validates_presence_of :first_name, :message => :missing_first_name
  validates_presence_of :last_name, :message => :missing_last_name
  validate :users_for_shared_access

  after_create  :increment_leads_count
  after_destroy :decrement_leads_count

  # Default values provided through class methods.
  #----------------------------------------------------------------------------
  def self.per_page ; 20                  ; end
  def self.outline  ; "long"              ; end
  def self.first_name_position ; "before" ; end

  # Save the lead along with its permissions.
  #----------------------------------------------------------------------------
  def save_with_permissions(params)
    self.campaign = Campaign.find(params[:campaign]) unless params[:campaign].blank?
    if self.access == "Campaign" && self.campaign # Copy campaign permissions.
      save_with_model_permissions(Campaign.find(self.campaign_id))
    else
      super(params[:users]) # invoke :save_with_permissions in plugin.
    end
  end

  # Update lead attributes taking care of campaign lead counters when necessary.
  #----------------------------------------------------------------------------
  def update_with_permissions(attributes, users)
    if self.campaign_id == attributes[:campaign_id] # Same campaign (if any).
      super(attributes, users)                      # See lib/fat_free_crm/permissions.rb
    else                                            # Campaign has been changed -- update lead counters...
      decrement_leads_count                         # ..for the old campaign...
      lead = super(attributes, users)               # Assign new campaign.
      increment_leads_count                         # ...and now for the new campaign.
      lead
    end
  end

  # Promote the lead by creating contact and optional opportunity. Upon
  # successful promotion Lead status gets set to :converted.
  #----------------------------------------------------------------------------
  def promote(params)
    account     = Account.create_or_select_for(self, params[:account], params[:users])
    opportunity = Opportunity.create_for(self, account, params[:opportunity], params[:users])
    contact     = Contact.create_for(self, account, opportunity, params)

    return account, opportunity, contact
  end

  #----------------------------------------------------------------------------
  def convert
    update_attribute(:status, "converted")
  end

  #----------------------------------------------------------------------------
  def reject
    update_attribute(:status, "rejected")
  end

  # Attach a task to the lead if it hasn't been attached already.
  #----------------------------------------------------------------------------
  def attach!(task)
    unless self.task_ids.include?(task.id)
      self.tasks << task
    end
  end

  # Discard a task from the lead.
  #----------------------------------------------------------------------------
  def discard!(task)
    task.update_attribute(:asset, nil)
  end

  #----------------------------------------------------------------------------
  def full_name(format = nil)
    if format.nil? || format == "before"
      "#{self.first_name} #{self.last_name}"
    else
      "#{self.last_name}, #{self.first_name}"
    end
  end
  alias :name :full_name

  private
  #----------------------------------------------------------------------------
  def increment_leads_count
    if self.campaign_id
      Campaign.increment_counter(:leads_count, self.campaign_id)
    end
  end

  #----------------------------------------------------------------------------
  def decrement_leads_count
    if self.campaign_id
      Campaign.decrement_counter(:leads_count, self.campaign_id)
    end
  end

  # Make sure at least one user has been selected if the lead is being shared.
  #----------------------------------------------------------------------------
  def users_for_shared_access
    errors.add(:access, :share_lead) if self[:access] == "Shared" && !self.permissions.any?
  end

end

app/models/user.rb
# Fat Free CRM
# Copyright (C) 2008-2010 by Michael Dvorkin
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

# == Schema Information
# Schema version: 27
#
# Table name: users
#
#  id                :integer(4)      not null, primary key
#  username          :string(32)      default(""), not null
#  email             :string(64)      default(""), not null
#  first_name        :string(32)
#  last_name         :string(32)
#  title             :string(64)
#  company           :string(64)
#  alt_email         :string(64)
#  phone             :string(32)
#  mobile            :string(32)
#  aim               :string(32)
#  yahoo             :string(32)
#  google            :string(32)
#  skype             :string(32)
#  password_hash     :string(255)     default(""), not null
#  password_salt     :string(255)     default(""), not null
#  persistence_token :string(255)     default(""), not null
#  perishable_token  :string(255)     default(""), not null
#  last_request_at   :datetime
#  last_login_at     :datetime
#  current_login_at  :datetime
#  last_login_ip     :string(255)
#  current_login_ip  :string(255)
#  login_count       :integer(4)      default(0), not null
#  deleted_at        :datetime
#  created_at        :datetime
#  updated_at        :datetime
#  admin             :boolean(1)      not null
#  suspended_at      :datetime
#
class User < ActiveRecord::Base
  attr_protected :admin, :suspended_at

  before_create  :check_if_needs_approval
  before_destroy :check_if_current_user, :check_if_has_related_assets

  has_one     :avatar, :as => :entity, :dependent => :destroy  # Personal avatar.
  has_many    :avatars                                         # As owner who uploaded it, ex. Contact avatar.
  has_many    :comments, :as => :commentable                   # As owner who crated a comment.
  has_many    :accounts
  has_many    :campaigns
  has_many    :leads
  has_many    :contacts
  has_many    :opportunities
  has_many    :activities,  :dependent => :destroy
  has_many    :permissions, :dependent => :destroy
  has_many    :preferences, :dependent => :destroy
  named_scope :except, lambda { |user| { :conditions => [ "id != ? ", user.id ] } }
  named_scope :by_name, :order => "first_name, last_name, email"
  default_scope :order => "id DESC" # Show newest users first.

  simple_column_search :username, :first_name, :last_name, :escape => lambda { |query| query.gsub(/[^\w\s\-\.']/, "").strip }

  acts_as_paranoid
  acts_as_authentic do |c|
    c.session_class = Authentication
    c.validates_uniqueness_of_login_field_options = { :message => :username_taken }
    c.validates_uniqueness_of_email_field_options = { :message => :email_in_use }
    c.validates_length_of_password_field_options  = { :minimum => 0, :allow_blank => true, :if => :require_password? }
    c.ignore_blank_passwords = true
  end

  # Store current user in the class so we could access it from the activity
  # observer without extra authentication query.
  cattr_accessor :current_user

  validates_presence_of :username, :message => :missing_username
  validates_presence_of :email,    :message => :missing_email

  #----------------------------------------------------------------------------
  def name
    self.first_name.blank? ? self.username : self.first_name
  end

  #----------------------------------------------------------------------------
  def full_name
    self.first_name.blank? || self.last_name.blank? ? self.email : "#{self.first_name} #{self.last_name}"
  end

  #----------------------------------------------------------------------------
  def suspended?
    self.suspended_at != nil
  end

  #----------------------------------------------------------------------------
  def awaits_approval?
    self.suspended? && self.login_count == 0 && Setting.user_signup == :needs_approval
  end

  #----------------------------------------------------------------------------
  def preference
    Preference.new(:user => self)
  end
  alias :pref :preference

  #----------------------------------------------------------------------------
  def deliver_password_reset_instructions!
    reset_perishable_token!
    Notifier.deliver_password_reset_instructions(self)
  end


  private

  # Suspend newly created user if signup requires an approval.
  #----------------------------------------------------------------------------
  def check_if_needs_approval
    self.suspended_at = Time.now if Setting.user_signup == :needs_approval && !self.admin
  end

  # Prevent current user from deleting herself.
  #----------------------------------------------------------------------------
  def check_if_current_user
    User.current_user && User.current_user != self
  end

  # Prevent deleting a user unless she has no artifacts left.
  #----------------------------------------------------------------------------
  def check_if_has_related_assets
    artifacts = %w(Account Campaign Lead Contact Opportunity Comment).inject(0) do |sum, asset|
      klass = asset.constantize
      sum += klass.assigned_to(self).count if asset != "Comment"
      sum += klass.created_by(self).count
    end
    artifacts == 0
  end

end

app/helpers/comments_helper.rb
# Fat Free CRM
# Copyright (C) 2008-2010 by Michael Dvorkin
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#------------------------------------------------------------------------------

module CommentsHelper
end

app/views/comments/_comment.html.haml
- truncated = simple_format h(truncate(comment.comment.gsub("\n", " "), :length => 125))
- formatted = simple_format h(comment.comment)
- collapsable = formatted.size > 150

%li[comment]{ highlightable(dom_id(comment, :tools), :off => "#f2f2f2") }
  .body
    = link_to avatar_for(comment.user, :size => "25x25"), user_path(comment.user)
    .tools{ invisible, :id => dom_id(comment, :tools) }
      = link_to_edit(comment) + " | "
      = link_to_delete(comment)

    = link_to(comment.user.full_name, user_path(comment.user)) + ","
    %tt
      added note #{t(:time_ago, distance_of_time_in_words(Time.now, comment.created_at))} (#{comment.created_at.strftime('%b %e, %Y')})
      - if collapsable
        = " | " + link_to_function(comment.collapsed? ? t(:more) : t(:less), "crm.flip_note_or_email(this, '#{t(:more)}', '#{t(:less)}')", :class => "toggle")

    - if collapsable
      %dt{ hidden_if(comment.expanded?), :id => dom_id(comment, :truncated) }
        = truncated
      %dt{ hidden_if(comment.collapsed?), :id => dom_id(comment, :formatted) }
        = auto_link(formatted)
    - else
      %dt= auto_link(formatted)

app/views/comments/_edit.html.haml
- class_name = commentable.class.name.downcase
.comment{:style => "margin: 5px 0px 0px 0px"}
  = link_to avatar_for(@current_user, :size => "25x25"), user_path(@current_user)
  - remote_form_for(@comment) do |f|
    = hidden_field_tag "comment[user_id]", @comment.user_id || @current_user.id
    = hidden_field_tag "comment[commentable_id]", commentable.id
    = hidden_field_tag "comment[commentable_type]", class_name.capitalize
    = f.text_area :comment, :id => dom_id(@comment, :text)
    %div{:style => "padding:6px 0px 0px 40px;"}
      = f.submit t(:save_note)
      #{t :or}
      = link_to_remote(t(:cancel), :url => send("edit_#{class_name}_comment_url", commentable), :method => :get, :with => "'cancel=true'")

app/views/comments/_new.html.haml
- class_name = commentable.class.name.downcase
.comment#comment_new{ highlightable(:comment_new_tools, :off => "#f2f2f2") }

  -# Two hidden fields store the IDs of notes and emails shown for the asset. These IDs are used
  -# by [Expand/Collapse All]. The contents gets updated by actions such as [Add] or [Delete].
  = hidden_field_tag :shown_notes, "#{commentable.comment_ids.join(',')}"
  = hidden_field_tag :shown_emails, "#{commentable.email_ids.join(',')}"

  = link_to avatar_for(@current_user, :size => "25x25"), user_path(@current_user)
  .tools#comment_new_tools{ invisible }
    = link_to_function("Expand All", "crm.flip_notes_and_emails('Expanded', 'More...', 'Less...')") << " | "
    = link_to_function("Collapse All", "crm.flip_notes_and_emails('Collapsed', 'More...', 'Less...')")

  #post{ hidden_if(session["#{class_name}_new_comment"].nil?) }
    - remote_form_for(@comment) do |f|
      = hidden_field_tag "comment[user_id]", @current_user.id
      = hidden_field_tag "comment[commentable_id]", commentable.id
      = hidden_field_tag "comment[commentable_type]", class_name.capitalize
      = f.text_area :comment
      %div{:style => "padding:6px 0px 0px 40px;"}
        = f.submit t(:add_note)
        #{t :or}
        = link_to_remote(t(:cancel), :url => send("new_#{class_name}_comment_url", commentable), :method => :get, :with => "'cancel=true'")
  #ask{ hidden_if(session["#{class_name}_new_comment"])}
    = text_field_tag :post_new_note, t(:add_note_help), :onclick => remote_function(:url => send("new_#{class_name}_comment_url", commentable), :method => :get)

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
  </tr>

<% for comment in @comments %>
  <tr>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New comment', new_comment_path %>

app/views/comments/show.html.erb
<%= link_to t(:edit), edit_comment_path(@comment) %> |
<%= link_to t(:back), comments_path %>